#define LEFT 1
#define RIGHT 2
#define JUSTIFY 3
#define INNAME 1
#define OUTNAME 2
#define WIDTH 3
#define LAST_THING 4
#define ARG_LEFT 'l'
#define ARG_RIGHT 'r'
#define ARG_JUSTIFY 'j'
#define ARG_SLASH '/'
#define ARG_DASH '-'
#define NOINNAME 1
#define NOOUTNAME 2
#define BAD_WIDTH 3
#define BAD_PARM 4
#define BAD_OPTION 5
#define NAME_MISSING 6